// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visao;

#nullable disable

namespace Persistencia.Migrations
{
    [DbContext(typeof(UrnaEletronicaContext))]
    [Migration("20230619160925_VagasNull")]
    partial class VagasNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("CandidatosSegundoTurno", b =>
                {
                    b.Property<short>("CandidadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleicaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidadoId", "EleicaoId");

                    b.HasIndex("EleicaoId");

                    b.ToTable("CandidatosSegundoTurno");
                });

            modelBuilder.Entity("Model.Models.Candidato", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cargo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<short>("PartidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Candidato", (string)null);
                });

            modelBuilder.Entity("Model.Models.Eleicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPrimeiroTurno")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SegundoTurno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusEleicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEleicao")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Vagas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Eleicao", (string)null);
                });

            modelBuilder.Entity("Model.Models.Partido", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partido", (string)null);
                });

            modelBuilder.Entity("Model.Models.Voto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Branco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<short?>("CandidatoId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleicaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleicaoId");

                    b.ToTable("Voto", (string)null);
                });

            modelBuilder.Entity("CandidatosSegundoTurno", b =>
                {
                    b.HasOne("Model.Models.Candidato", null)
                        .WithMany()
                        .HasForeignKey("CandidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Models.Eleicao", null)
                        .WithMany()
                        .HasForeignKey("EleicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.Candidato", b =>
                {
                    b.HasOne("Model.Models.Partido", "Partido")
                        .WithMany("Candidatos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Model.Models.Voto", b =>
                {
                    b.HasOne("Model.Models.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Model.Models.Eleicao", "Eleicao")
                        .WithMany("Votos")
                        .HasForeignKey("EleicaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleicao");
                });

            modelBuilder.Entity("Model.Models.Candidato", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Model.Models.Eleicao", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Model.Models.Partido", b =>
                {
                    b.Navigation("Candidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
